### ISSUE TITLE
Memory usage is not correct.

### ISSUE THREAD

**Issue by LangInteger** [tianshiyeben/wgcloud#10]
The correct memory usage:

![image](https://user-images.githubusercontent.com/17768055/75089864-155c9380-5598-11ea-8c83-966fa2de891e.png)

displayed in wgcloud:

![image](https://user-images.githubusercontent.com/17768055/75089946-e7c41a00-5598-11ea-97e0-44843bdc73fd.png)

I think there maybe a more reasonable method to calculate memory usage like [this](https://pitstop.manageengine.com/portal/kb/articles/how-is-memory-utilization-calculated-for-linux-servers) with formula:

> Memory Utilization (%) = 100 -(((MemFree + Buffers + Cached)*100)/maxValue)

 not simply `1 - free/total`, which scared me.

**Comment by tianshiyeben** [comment]
Thank you. I think you're right. I'll fix it.

**Comment by tianshiyeben** [comment]
我查过关于sigar资料，used包含 buffers和cached

**Comment by tianshiyeben** [comment]
I've verified it. Now it seems that it should be correct. You can test the code again. Maybe you can improve the code and send the improved code here later.

**Comment by LangInteger** [comment]
Where did you get access to sigar doc, the [official wiki](http://sigar.hyperic.com/) doesn't response to me.

**Comment by LangInteger** [comment]
> I checked the sigar data. Used includes buffers and cached
> ，And I've verified that it's right, with very little error

With this theory, the calculation process is right.

- My machine get s 1.0GB memory in total, with 116MB free , so the `used + cached/buffered` is 907, leads to 907/1024 = 88% memory usage.

But as I said,

> I think there maybe a more reasonable method to calculate memory usage like [this](https://pitstop.manageengine.com/portal/kb/articles/how-is-memory-utilization-calculated-for-linux-servers) with formula:
> Memory Utilization (%) = 100 -(((MemFree + Buffers + Cached)*100)/maxValue)

The key point is that I think the buffered/cached memory should not be calculated into used memory, it's still can be applied for new applications. Some reference:

- [Meaning of the buffers/cache line in the output of free](https://serverfault.com/a/85481):
  - It gives the original value for used minus the sum buffers+cached and the original value for free plus the sum buffers+cached, hence its title. These new values are often more meaningful

**Comment by LangInteger** [comment]
As for the code part, I can't see the buffered/cached memory field via the decompiled sigar source code. 

```java
public class Mem implements Serializable {
  private static final long serialVersionUID = 10181L;
  long total = 0L;
  long ram = 0L;
  long used = 0L;
  long free = 0L;
  long actualUsed = 0L;
  long actualFree = 0L;
  double usedPercent = 0.0D;
  double freePercent = 0.0D;

  public Mem() {
  }
}
```

You may give the actualUsed /actualFree  a try, they may give us a more meaningful result.

**Comment by tianshiyeben** [comment]
可以用中文交流吗，我也不是专业运维工程师，也在交流和学习。
要不我们先关闭这个issue吧，等有好的解决方案时候再修复它。可以吗

**Comment by LangInteger** [comment]
可以，我觉得 sigar 的 Mem 类提供的  actualUsed /actualFree 就挺像是修正后的已使用内存/未使用内存。得空我验证下。

用英文是因为很多名词我翻译的不好，容易理解偏差。

**Comment by LangInteger** [comment]
上面提到的资料：

- [Meaning of the buffers/cache line in the output of free](https://serverfault.com/a/85481):

值得一看

**Comment by LangInteger** [comment]
另外，sigar 这个类库好老了，我看快十年没动代码了。

**Comment by tianshiyeben** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Liu Lang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上10:04
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"val"<tianshiyeben@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tianshiyeben/wgcloud] Memory usage is not correct. (#10)




上面提到的资料：
  
Meaning of the buffers/cache line in the output of free:
  
值得一看

**Comment by tianshiyeben** [comment]
是的



---Original---
