### ISSUE TITLE
进程管理

### ISSUE THREAD

**Issue by w-copper** [tianshiyeben/wgcloud#14]
能否在添加监控进程时采用关键字搜索的方式

**Comment by tianshiyeben** [comment]
你是说搜索IP吗，现在就可以搜索啊，输入关键字时候会自动完成

**Comment by w-copper** [comment]
不是的，是在添加进程管理的时候
![image](https://user-images.githubusercontent.com/35824834/83101948-0d0b7b80-a0e6-11ea-8c8b-d7d34175e1ea.png)

**Comment by tianshiyeben** [comment]
我明白了，你是说进程id 自动填充完成，是吧。

**Comment by w-copper** [comment]
> 我明白了，你是说进程id 自动填充完成，是吧。

自动填充，也不像。比如说，我想监控nginx，然后可以提供一个搜索按钮，搜索nginx关键词，然后选择进程，确认

**Comment by tianshiyeben** [comment]
嗯，理解你的意思了。这个要研究下，看能不能搞。

**Comment by w-copper** [comment]
好的，祝你们越做越好~
