### ISSUE TITLE
大佬您好!请问一下健康检查是多久轮询一下健康检查的地址?可以修改轮询的时间嘛?

### ISSUE THREAD

**Issue by openbytes** [tianshiyeben/wgcloud#15]

**Comment by tianshiyeben** [comment]
可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"openbytes"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 中午12:16
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] 大佬您好!请问一下健康检查是多久轮询一下健康检查的地址?可以修改轮询的时间嘛? (#15)

**Comment by openbytes** [comment]
找到了.在这里.谢谢您.
![image](https://user-images.githubusercontent.com/34796404/83221175-ac447780-a1a7-11ea-9fbb-943bbb06c9aa.png)
