### ISSUE TITLE
请问下，能否加入微信企业号的告警推送接口哈？

### ISSUE THREAD

**Issue by lgs3137** [tianshiyeben/wgcloud#16]
请问下，能否加入微信企业号的告警推送接口哈？

**Comment by tianshiyeben** [comment]
可以自己实现，下版我加了推送接口，可以在shell调用自己的扩展接口实现。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lgs3137"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 上午9:53
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] 请问下，能否加入微信企业号的告警推送接口哈？ (#16)





 
请问下，能否加入微信企业号的告警推送接口哈？

**Comment by lgs3137** [comment]
ok,加入接口的话就可以自行脚本实现了~
另外咨询下，自定义触发告警指标近期版本会不会考虑加入呢？

**Comment by tianshiyeben** [comment]
自定义触发告警指标？


现在有自定义配置，你看看配置文件最下面，那堆参数


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lgs3137"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 上午10:22
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"val"<tianshiyeben@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tianshiyeben/wgcloud] 请问下，能否加入微信企业号的告警推送接口哈？ (#16)





 
ok,加入接口的话就可以自行脚本实现了~
 另外咨询下，自定义触发告警指标近期版本会不会考虑加入呢？

**Comment by lgs3137** [comment]
好的，看到了~
感谢~
