### ISSUE TITLE
获取主机温度失败

### ISSUE THREAD

**Issue by salamander-mh** [tianshiyeben/wgcloud#27]
日志里看到的
```
hostUtil.go:75: GetHostTemperatures err： Number of warnings: 1
```
系统：
```
Ubuntu 20.04.1 LTS
CPU model name	: AMD Ryzen 7 5800X 8-Core Processor
```

**Comment by tianshiyeben** [comment]
这是什么操作系统？



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 下午4:55
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tianshiyeben/wgcloud] 获取主机温度失败 (#27)




 
日志里看到的
 hostUtil.go:75: GetHostTemperatures err： Number of warnings: 1

**Comment by salamander-mh** [comment]
@tianshiyeben 
**Ubuntu 20.04.1 LTS**
还有个问题，我的nginx配上https代理后，上报就会出问题了。
