### ISSUE TITLE
loop device用不着报警吧？

### ISSUE THREAD

**Issue by salamander-mh** [tianshiyeben/wgcloud#28]
类型这样的`/dev/loop2`

**Comment by tianshiyeben** [comment]
可以在server/config/application.yml配置，屏蔽不需要告警的磁盘


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 上午10:49
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] loop device用不着报警吧？ (#28)





 
类型这样的/dev/loop2

**Comment by salamander-mh** [comment]
我的环回设备有30多个`/dev/loop7`，每个都要填过去吗？
我看到配置里已经写了`diskBlock: /dev`，这个会匹配吗？

**Comment by tianshiyeben** [comment]
后天发布v3.3.0，这个版本支持/dev/**通配符这样写，等两天哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 中午12:09
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"val"<tianshiyeben@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tianshiyeben/wgcloud] loop device用不着报警吧？ (#28)





 
我的环回设备有30多个/dev/loop7，每个都要填过去吗？
 我看到配置里已经写了diskBlock: /dev，这个会匹配吗？

**Comment by salamander-mh** [comment]
好的，谢谢大佬。

**Comment by salamander-mh** [comment]
@tianshiyeben  我已经升级了3.0.0，然后也配置了
```
diskBlock: /dev/**
```
但是，磁盘还在告警：
```
磁盘/snap/snap-store/498使用率为100.0%，超过告警值99.0%，可能存在异常
```

**Comment by tianshiyeben** [comment]
应该配置这样：/snap/**




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 上午10:57
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"val"<tianshiyeben@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tianshiyeben/wgcloud] loop device用不着报警吧？ (#28)





 
@tianshiyeben  我已经升级了3.0.0，然后也配置了
 diskBlock: /dev/**  
但是，磁盘还在告警：
 磁盘/snap/snap-store/498使用率为100.0%，超过告警值99.0%，可能存在异常

**Comment by salamander-mh** [comment]
@tianshiyeben  哦哦，我错了。
