### ISSUE TITLE
主机已下线告警要过10几分钟才有？

### ISSUE THREAD

**Issue by salamander-mh** [tianshiyeben/wgcloud#29]
这个有配置的地方吗？这个通知时间有点长。

**Comment by tianshiyeben** [comment]
对，10分钟不上报数据，才能判定主机下线了。现在不能配置



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月4日(周四) 下午2:33
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tianshiyeben/wgcloud] 主机已下线告警要过10几分钟才有？ (#29)




 
这个有配置的地方吗？这个通知时间有点长。

**Comment by salamander-mh** [comment]
大佬10分钟有点长，能配置个3，4分钟就好了。

**Comment by tianshiyeben** [comment]
让我想想哈，看缩短到几分钟合适



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月10日(周三) 上午9:39
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 主机已下线告警要过10几分钟才有？ (#29)




 
大佬10分钟有点长，能配置个3，4分钟就好了。

**Comment by salamander-mh** [comment]
@tianshiyeben  谢谢大佬。

**Comment by tianshiyeben** [comment]
不要客气，互相学习



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月10日(周三) 晚上9:22
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 主机已下线告警要过10几分钟才有？ (#29)




 
@tianshiyeben  谢谢大佬。
