### ISSUE TITLE
企业微信机器人告警信息没有发送成功

### ISSUE THREAD

**Issue by salamander-mh** [tianshiyeben/wgcloud#30]
大佬你好，我照你的脚本写了写：
```
#!/bin/bash
# -*- coding: utf-8 -*-

content=${@:1}
content=${content//\<font color=\'red\'\>/}
content=${content//\<\/font\>\<\/br\>/}

echo "告警信息 : $content"

wx() {
  local Msg="告警信息:$1"

   curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=**********************' \
   -H 'Content-Type: application/json' \
   -d '
   {
        "msgtype": "text",
        "text": {
            "content": "'${Msg}'"
        }
   }'
}

wx $content
```
这个发送到企业微信群里的告警，但是结果是
```
告警信息:
```
后面的具体告警信息没了。。

**Comment by tianshiyeben** [comment]
这个脚本，你在哪儿看的呢，给我看下地址



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月5日(周五) 下午5:08
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tianshiyeben/wgcloud] 企业微信机器人没有发送成功 (#30)




 
大佬你好，我照你的脚本写了写：
 #!/bin/bash # -*- coding: utf-8 -*- content=${@:1} content=${content//\<font color=\'red\'\&gt;/} content=${content//\<\/font\&gt;\<\/br\&gt;/} echo "告警信息 : $content" wx() {   local Msg="告警信息:$1"    curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=**********************' \    -H 'Content-Type: application/json' \    -d '    {         "msgtype": "text",         "text": {             "content": "'${Msg}'"         }    }' } wx $content  
这个发送到企业微信群里的告警，但是结果是
 告警信息:  
后面的具体告警信息没了。。

**Comment by salamander-mh** [comment]
就是这篇博客：
[微信告警](https://blog.csdn.net/tianshiyeben/article/details/108959637)

**Comment by tianshiyeben** [comment]
少了脚本25行那句，加上试下



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月5日(周五) 晚上6:08
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 企业微信机器人告警信息没有发送成功 (#30)




 
就是这篇博客：
 微信告警

**Comment by salamander-mh** [comment]
@tianshiyeben   这个脚本我用`weixin.sh 错误发生了`这样的方式是可以发送的

**Comment by tianshiyeben** [comment]
local Msg="告警信息:$1"
&nbsp; &nbsp;Msg=${Msg//\"/}


你看是不是少了第二行



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月5日(周五) 晚上9:17
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 企业微信机器人告警信息没有发送成功 (#30)




 
@tianshiyeben   这个脚本我用weixin.sh 错误发生了这样的方式是可以发送的

**Comment by salamander-mh** [comment]
不太懂
```
Msg=${Msg//\"/}
```
这是啥操作

**Comment by tianshiyeben** [comment]
替换双引号



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月6日(周六) 下午3:50
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 企业微信机器人告警信息没有发送成功 (#30)




 
不太懂
 Msg=${Msg//\"/}  
这是啥操作

**Comment by salamander-mh** [comment]
好的，感谢大佬！
