### ISSUE TITLE
dns的问题？

### ISSUE THREAD

**Issue by salamander-mh** [tianshiyeben/wgcloud#31]
这个程序会自己添加一个DNS服务器吗？我看到`/etc/resolv.conf`里多个一个
```
nameserver 127.0.0.53
```
有时候上报失败了，是在这个server上的。

**Comment by tianshiyeben** [comment]
不会，agent只读不写



---原始邮件---
发件人: "Salamander"<notifications@github.com&gt;
发送时间: 2021年2月22日(周一) 上午9:37
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tianshiyeben/wgcloud] dns的问题？ (#31)




 
这个程序会自己添加一个DNS服务器吗？我看到/etc/resolv.conf里多个一个
 nameserver 127.0.0.53

**Comment by salamander-mh** [comment]
好的。
