### ISSUE TITLE
想请教一下windows远程是基于什么来做的？

### ISSUE THREAD

**Issue by birkh8792** [tianshiyeben/wgcloud#33]

**Comment by tianshiyeben** [comment]
你好，windows远程我们没有开发对应应用软件，需要用户自己在windows上安装远程服务工具，我们通过跳转到服务url来实现windows远程。





Good luck


WGCLOUD


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 下午5:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] 想请教一下windows远程是基于什么来做的？ (#33)
