### ISSUE TITLE
DeskState.java ---> DiskState.java 

### ISSUE THREAD

**Issue by mrvance** [tianshiyeben/wgcloud#38]
拼写错误，强迫症患者前来报到。

**Comment by tianshiyeben** [comment]
明白，谢谢你



Good luck


WGCLOUD


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 下午4:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] DeskState.java ---&gt; DiskState.java  (Issue #38)





 
拼写错误，强迫症患者前来报到。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
