### ISSUE TITLE
代码有些地方不完美帮你修改了一下

### ISSUE THREAD

**Issue by LiuTianP** [tianshiyeben/wgcloud#4]
public static String doCommond(Connection conn, String cmd) {
        String result = "";
        
        if (conn == null) {
            System.out.println("请先链接服务器");
        } else {
            Session sess = null;
            try {
                sess = conn.openSession();
                sess.execCommand(cmd);
                try (BufferedReader stdoutReader = new BufferedReader(new InputStreamReader(new StreamGobbler(sess.getStdout())));) {
                    while (true) {
                        String line = stdoutReader.readLine();
                        if (line == null) {
                            break;
                        }
                        result += line + StaticKeys.SPLIT_BR;
                    }
                }
            } catch (IOException e) {
                System.out.println("执行linux命令错误：" + e);
            } finally {
                if (sess != null) {
                    sess.close();
                }
            }
        }
        
        if (result.endsWith(StaticKeys.SPLIT_BR)) {
            result = result.substring(0, result.length() - StaticKeys.SPLIT_BR.length());
        }
        
        if (!StringUtils.isEmpty(result)) {
            if (cmd.contains("DEV") || cmd.contains("iostat")) {
                if (result.contains("</br></br>")) {
                    result = result.substring(result.lastIndexOf("</br></br>") + 10);
                }
            }
            if (cmd.contains("mpstat")) {
                if (result.contains("</br></br>")) {
                    result = result.substring(result.lastIndexOf("</br></br>") + 10);
                    int s = result.indexOf("</br>") + 5;
                    s = result.indexOf("</br>", s);
                    result = result.substring(0, s);
                }
            }
        }
        
        return result;
    }

你之前的代码如果抛异常的话连接和BufferReader是关闭不了的

**Comment by tianshiyeben** [comment]
tks，已合到代码里。
