### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [tianshiyeben/wgcloud#41]
Hey there!

I belong to an open source security research community, and a member (@hi-unc1e) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by tianshiyeben** [comment]
Thank you very much. Please send the question to email tianshiyeben@qq.com

**Comment by JamieSlome** [comment]
@tianshiyeben - we actually sent an e-mail to you about 1 hour ago to the mentioned e-mail address. Did you receive this?

Just for reference, you can find the report [here](https://huntr.dev/bounties/10bf77c6-4973-4915-a761-a12d15715303/). It is private and only accessible to you 👍 Let me know if you have any questions.

**Comment by tianshiyeben** [comment]
Thank you very much. I have received it. I will think about how to deal with this problem

**Comment by JamieSlome** [comment]
@tianshiyeben - great! Please take your time, and feel free to ask @hi-unc1e for support in the thread 👍

**Comment by tianshiyeben** [comment]
ok ok  tks @hi-unc1e

**Comment by tianshiyeben** [comment]
Thank you very much for your suggestions. I already know how to fix it and have started to make some updates
