### ISSUE TITLE
对于Wgcloud的几个疑问？

### ISSUE THREAD

**Issue by stone-98** [tianshiyeben/wgcloud#42]
十分感谢作者，开源这个项目，给我的帮助很大，但是有一些疑问，请指教。

我目前需要实现几个功能：
- 指定子网，自动发现网络设备，并且画出网络拓扑图，类似于我指定一个网段，自动发现这个网段下的设备，以及自动画出此网段的网络拓扑图。（能发现对应的网络设备，如交换机，路由器等等）
- 实现对主机信息的自动采集（cpu、网络接口、磁盘等等信息，并且支持多种操作系统）

在演示的界面中我只发现了主机拓扑，主机拓扑的发现应该是通过agent实现，它描述的仅仅是Server和监控的主机之间的关联。目前wgcloud是否暂时不能满足我的需求？

- 对于主机信息的采集，我大概了解的几种方案：
  - Prometheus
  - SSH
  - SNMP
  - Agent

#### 基于Prometheus对主机进行采集的方式
通过Prometheus进行监控主机信息，需要在对应的主机安装node-exporter，但是node-exporter本身支持的指标十分有限，大都都是监控信息，并不能满足现有的需求，虽然它可以通过`--collector.textfile.directory`指定从本地磁盘获取监控数据，再定义脚本获取对应的指标定时更新磁盘，从而实现对主机信息的采集。但是这种方式依赖Prometheus和node-exporter的安装，并且还需要自定义脚本，过于麻烦。

#### 基于SSH对主机进行采集的方式
定义对应的脚本，然后通过SSH的方式对主机进行监控，目前我了解的开源监控系统中，Zabbix支持这种方式，通过SSH对目标主机进行采集。但是需要对不同的操作系统进行兼容。

#### 基于SNMP对主机进行采集的方式
在对应的主机安装SNMP服务，SNMP服务是十分轻量级的，然后Server通过SNMP协议对目标主机进行采集。

##### 基于JAVA开发
通过Agent对服务器进行采集，因为考虑到技术栈的原因，目前只能使用Java进行开发。
- JDK自带的库
获取信息不够全面，不能满足现有需求。
- Sigar库
底层基于JNI，需要在不同的操作系统下引入不同的DLL库，侵入性较高，并且从16年已经没有更新记录，停止维护。
- OSHI库
OSHI 是一个免费的基于 JNA（本机）的 Java 操作系统和硬件信息库。它不需要安装任何额外的本地库，旨在提供跨平台实现来检索系统信息，例如操作系统版本、进程、内存和 CPU 使用率、磁盘和分区、设备、传感器等。支持Windows • Linux • macOS • Unix（AIX、FreeBSD、OpenBSD、Solaris）系统，社区活跃。

##### 基于GO开发

我对JAVA更加熟悉，我的理解是使用GO能获取到的指标，使用JAVA应该也能获取到，可能区别就是性能上的差距，以及JAVA需要依赖JDK。我的理解对吗？

基于上述的描述，如果我理解的没有的话，我打算采用两种方案进行开发对主机信息的采集：
- 自主开发Agent：使用JAVA语言，采用OSHI库
- 基于SNMP

您对我有什么建议吗？

**Comment by tianshiyeben** [comment]
感谢关注，非常高兴能帮到你

**Comment by tianshiyeben** [comment]
但是我可能无法提供具体的建议

**Comment by tianshiyeben** [comment]
你好，基本就是这样的



---原始邮件---
发件人: "stone ***@***.***&gt;
发送时间: 2022年4月11日(周一) 上午9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tianshiyeben/wgcloud] 对于Wgcloud的几个疑问？ (Issue #42)




 
@tianshiyeben 我想请教的是使用Go语言和使用Java语言进行开发，可能区别就是性能上的差距，以及JAVA需要依赖JDK。我的理解对吗？

**Comment by stone-98** [comment]
@tianshiyeben thanks
