### ISSUE TITLE
为什么使用Java做监控

### ISSUE THREAD

**Issue by hanizhong** [tianshiyeben/wgcloud#7]
你不觉用Java做监控不是很占资源吗，还有安装也不是很方便吧，每台机器都得安装jdk，还有如果是不使用docker部署项目的，还得考虑jdk兼容问题吧，监控系统建议使用C、C++、golang等这些语言更好，不用安装特定环境，server倒是无所谓

**Comment by tianshiyeben** [comment]
谢谢，go我还没研究过，等研究后再改进。
