### ISSUE TITLE
可以监控每个进程的网络流量吗？

### ISSUE THREAD

**Issue by alex-jin** [tianshiyeben/wgcloud#76]

**Comment by tianshiyeben** [comment]
可以的



Good Luck


WGCLOUD


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午4:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] 可以监控每个进程的网络流量吗？ (Issue #76)

**Comment by alex-jin** [comment]
感谢回复
