### ISSUE TITLE
怎么配置和使用？

### ISSUE THREAD

**Issue by sawyerRick** [tianshiyeben/wgcloud#8]
# 需要配置哪些文件？
# 需要配置哪些信息？

**Comment by tianshiyeben** [comment]
https://www.wgstart.com/docs13.html，这个是安装和配置说明文档。

**Comment by sawyerRick** [comment]
404了------------------ 原始邮件 ------------------
发件人: "tianshiyeben"<notifications@github.com>
发送时间: 2020年2月20日(星期四) 下午2:01
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com>;
抄送: "sawyerRick"<1103031078@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tianshiyeben/wgcloud] 怎么配置和使用？ (#8)



https://www.wgstart.com/docs13.html，这个是安装和配置说明文档。
 
&mdash;

**Comment by tianshiyeben** [comment]
https://pan.baidu.com/s/1L0yxDBjnvcgR6sqjoPFxLw#list/path=%2Fwgcloud%E4%B8%8B%E8%BD%BD%2Fv2.3


这个是百度网盘，有个安装文档，你下载下来用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sawyerRick"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 下午2:49
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"val"<tianshiyeben@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [tianshiyeben/wgcloud] 怎么配置和使用？ (#8)



404了------------------ 原始邮件 ------------------ 
 发件人: "tianshiyeben"<notifications@github.com&gt; 
 发送时间: 2020年2月20日(星期四) 下午2:01 
 收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;; 
 抄送: "sawyerRick"<1103031078@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
 主题: Re: [tianshiyeben/wgcloud] 怎么配置和使用？ (#8) 
 
 
 
 https://www.wgstart.com/docs13.html，这个是安装和配置说明文档。 
   
 &amp;mdash;
