### ISSUE TITLE
agent怎么做到打包体积很小的呢

### ISSUE THREAD

**Issue by cctyl** [tianshiyeben/wgcloud#80]
我尝试下载release包，解压后发现agent可执行文件只有11兆，我自己编译打包后，得到的是24兆，这是为什么呢，是使用了graalvm 吗

**Comment by tianshiyeben** [comment]
你好：
&nbsp; &nbsp; &nbsp;开源版本（基于java开发）是这样的，你从网站下载的是商业版（基于go开发），两个不一样的



Good Luck


WGCLOUD


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月16日(星期三) 上午9:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] agent怎么做到打包体积很小的呢 (Issue #80)





 
我尝试下载release包，解压后发现agent可执行文件只有11兆，我自己编译打包后，得到的是24兆，这是为什么呢，是使用了graalvm 吗

**Comment by cctyl** [comment]
> 

哈哈好的，我尝试基于开源版本优化下体积
