### ISSUE TITLE
启动失败，没有日志

### ISSUE THREAD

**Issue by LangInteger** [tianshiyeben/wgcloud#9]
![image](https://user-images.githubusercontent.com/17768055/75087048-78d5c980-5576-11ea-8ad5-9baaad3ae56b.png)

**Comment by LangInteger** [comment]
原因是没有安装java，启动脚本可以给出更友好的提示

**Comment by tianshiyeben** [comment]
嗯，wgclou是用java开发的，所以运行的主机得安装jdk1.8。不过你说得对，启动脚本可以做的友好一些



---原始邮件---
发件人: "Liu Lang"<notifications@github.com&gt;
发送时间: 2020年2月22日(周六) 中午1:38
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 启动失败，没有日志 (#9)



Closed #9.
